name: push
on:
  push:
    tags:
      - "v*"

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@main

      - name: Set up Python 3.11
        uses: actions/setup-python@main
        with: { python-version: 3.11 }

      - name: Upgrade pip
        run: python -m pip install --upgrade pip PyInstaller

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: build
        run: pyinstaller -F app/main.py
  
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: sample-windows
          path: dist/rpa_for_windows.exe