name: Build Python Application with Nuitka on Windows

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Nuitka
        run: pip install nuitka

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Compile Python script with Nuitka
        run: nuitka --standalone --onefile app/main.py

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-Executable
          path: main.dist/main.exe
