name: Compile Python
on: [push]

jobs:

  build:
    # こちらはWindowsに対応しておりますわ。
    runs-on: windows-latest

    steps:

      # リポジトリをチェックアウトするのです
      - uses: actions/checkout@v3

      # Pythonのセットアップを行いますわ
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' # 使用するPythonのバージョンの範囲または正確なバージョンを、SemVerのバージョン範囲の構文を使用して指定しますわ
          architecture: 'x64' # オプションでx64またはx86を指定しますわ。指定がない場合はデフォルトでx64になりますわ

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Pythonスクリプトをスタンドアロンのexeにビルドしますわ
      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: app/main.py
          onefile: true
          tk-inter: true

      # アーティファクトをアップロードしますわ
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe
          path: build/main.exe
